apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: stresstest
  name: job-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
