apiVersion: v1
kind: Namespace
metadata:
  name: stresstest
  labels:
    # Tvinger på baseline Pod Security Standard
    pod-security.kubernetes.io/enforce: baseline
    # Auditing (logging) restricted Pod Security Standard
    pod-security.kubernetes.io/audit: restricted
    # Varsler om "restricted Pod Security Standard"
    pod-security.kubernetes.io/warn: restricted
