apiVersion: v1
kind: PersistentVolume
metadata:
  name: stresstest-pv
  namespace: stresstest
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/data"
