apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stresstest-pvc
  namespace: stresstest
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
