apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-rolebinding
  namespace: stresstest
subjects:
- kind: ServiceAccount
  name: job-service-account
  namespace: stresstest
roleRef:
  kind: Role
  name: job-role
  apiGroup: rbac.authorization.k8s.io

