apiVersion: batch/v1
kind: Job
metadata:
  name: stresstest
  namespace: stresstest
spec:
  template:
    metadata:
      labels:
        app: stresstest
    spec:
      serviceAccountName: job-service-account
      containers:
      - name: stresstest
        image: stresstest:v1
        volumeMounts:
        - mountPath: "/app/data"
          name: storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: stresstest-pvc
      restartPolicy: Never
  backoffLimit: 4
